<?php
$translate = $this->plugin('translate');
$this->htmlElement('body')->appendAttribute('class', 'assets search');
$form->prepare(); 
?>

<?php echo $this->pageTitle($translate('Advanced search'), 1, $translate('Assets')); ?>

<?php $this->trigger('view.browse.before'); ?>

<?php echo $this->form()->openTag($form); ?>
<div id="page-actions">
    <?php echo $this->hyperlink($translate('Reset'), $this->url(null, [], true), ['class' => 'button']); ?>
    
    <!-- use the setButtonLabel instead ?  in form ? where then function -->
    <button type="submit">
        <?php echo $this->escapeHtml($translate('Search')); ?>
    </button>
</div>
<?php echo $this->formCollectionElementGroups($form); ?>
<?php echo $this->form()->closeTag(); ?>

<?php $this->trigger('view.browse.after'); ?>

