<?php
$translate = $this->plugin('translate');
$escape = $this->plugin('escapeHtml');
?>
<h3>
    <?php echo $escape($resource->name());?>
</h3>

<?php echo $this->thumbnail($resource, 'square', ['class' => 'asset-inline']); ?>

<?php $results = []; ?>
<?php if ($resource_array): ?> 
    <div class="meta-group">
        <h4><?php echo $translate('Related to:'); ?></h4>
        <?php $result = [];?> 
        <?php  echo $this->RelatedRessourcesToAsset($resource_array); ?>
    </div>
<?php endif; ?>


<div class="meta-group">
    <h4><?php echo $translate('Media type'); ?></h4>
    <div class="value"><?php echo $escape($resource->mediaType()); ?></div>
</div>

<?php
$altText = $resource->altText();
if ($altText):
?>
<div class="meta-group">
    <h4><?php echo $translate('Alt text'); ?></h4>
    <div class="value"><?php echo $escape($resource->altText()); ?></div>
</div>
<?php endif; ?>

<?php $this->trigger('view.details', ['entity' => $resource]); ?>
