<?php
$translate = $this->plugin('translate');
$hyperlink = $this->plugin('hyperlink');
$escape = $this->plugin('escapeHtml');

$mappedResource = [
    'labels' => [
        'items' => 'item',
        'item_sets' => 'item-set',
    ],
    
    'display_titles' => [
        'item' => 'Items',
        'item-set' => 'Item sets',
        'media' => 'Media',
    ]
];

$results = [];

foreach ($resources as $resource) {

    $type = isset($mappedResource['labels'][$resource->getResourceName()]) ? $mappedResource['labels'][$resource->getResourceName()] : $resource->getResourceName();

    $title = $resource->getTitle();
    $id = $resource->getId();

    $output =  $hyperlink($title . '(' . $id . ')', $this->url('admin/default', ['controller' => $type, 'action' => 'browse'], ['query' => ['id' => $id]]));
    $results[$type][] = $output;
}
?>

<?php foreach ($results as $type => $values): ?>
    
    <div class="value">
        <?php if(isset($mappedResource['display_titles'][$type])): ?>
            <?= $escape($translate($mappedResource['display_titles'][$type]));?>
        <?php else: ?>
            <?= $escape($translate($type));?>
        <?php endif; ?>
    </div> 

    <div class="value">
        <?php foreach ($values as $value): ?>
            <?= $value ?><br>
        <?php endforeach; ?>
    </div>
    
<?php endforeach; ?>
