<?php
$translate = $this->plugin('translate');
$hyperlink = $this->plugin('hyperlink');

    $mappedResource = [
        
        'labels' => [
            'items' => 'item',
            'item_sets' => 'item-set',
        ],
        
        'display_titles' => [
            'item' => 'Items',
            'item-set' => 'Item sets',
            'media' => 'Medias',
        ]
    ];
    
    $results = []; 

    foreach ($resources as $resource) {

        $type = isset($mappedResource['labels'][$resource->getResourceName()]) ? $mappedResource['labels'][$resource->getResourceName()] : $resource->getResourceName();

        $title = $resource->getTitle();
        $id = $resource->getId();

        $output =  $hyperlink($title . '(' . $id . ')', $this->url('admin/default', ['controller' => $type, 'action' => 'browse'], ['query' => ['id' => $id]]));
        $results[$type][] = $output;
    }

    foreach ($results as $type => $values){
  
        echo '<div class="value">';
        echo $translate($mappedResource['display_titles'][$type]);
        echo '</div>'; 

        echo '<div class="value">';

        foreach ($values as $value) {
            echo $value . '<br>';
        }
        echo '</div>';
    }
?>
